---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sateales/public_html/tealblocks/wp-content/themes/tealblank
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp functions.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R template-parts $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH

    