---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sateales/public_html/tealblocks/wp-content/themes/tealblank
    - /bin/cp /home/sateales/repositories/tealblank-theme/style.css $DEPLOYPATH
    - /bin/cp /home/sateales/repositories/tealblank-theme/functions.php $DEPLOYPATH
    - /bin/cp /home/sateales/repositories/tealblank-theme/index.php $DEPLOYPATH

    